// CONSTANTS

// GAME BACKGROUNDS
const CANVAS_WIDTH = 400;
const CANVAS_HEIGTH = 600;
const WALL_WIDTH = 16;
const CEILING_HEIGHT = 16;

// GAME
const INITIAL_GAME_SPEED = 1.5;
const MAX_GAME_SPEED = 3;
const GAME_SPEED_FRAME_RATE = 600;
const GAME_SPEED_RATE = 0.2;
const INITIAL_PLATFORM_FRAME_RATE = 70;
const PLATFORM_FRAME_RATE = 3;
const GRAVITY = 0.1;
const INCREASE_LIFE_RATE = 2;
const DECREASE_LIFE_RATE = 3;
const SCORE_FRAME_RATE = 120;

// SPRITE FRAME
const SPRITE_FRAME_RATE = 10;
const INITIAL_SPRITE_FRAME = 0;
const MAX_SPRITE_FRAME = 3;
const MAX_SPIKE_SPRITE_FRAME = 1;
const MAX_CONVEYOR_SPRITE_FRAME = 3;
const MAX_TRAMPOLINE_SPRITE_FRAME = 4;
const MAX_FAKE_SPRITE_FRAME = 5;

// PLAYER
const PLAYER_WIDTH = 32;
const PLAYER_HEIGHT = 32;
const INITIAL_LIFE = 10;
const MAX_LIFE = 10;
const MIN_LIFE = 0;
const PLAYER_MOVE_SPEED = 5;
const INITIAL_PLAYER_POSITION_X = 184;
const INITIAL_PLAYER_POSITION_Y = 200;

// PLAYER SPRITE FRAME
const INITIAL_PLAYER_FRAME_X = 0;
const INITIAL_PLAYER_FRAME_Y = 4;
const PLAYER_LEFT_FRAME = 0;
const PLAYER_RIGHT_FRAME = 1;
const PLAYER_FALLING_FRAME = 4;
const PLAYER_STANDING_FRAME = 8;

// PLATFORMS
const PLATFORM_FRAME_X = 0;
const PLATFORM_FRAME_Y = 0;
const SHAFT_WIDTH = 95;
const SHAFT_HEIGHT = 16;
const SPIKE_WIDTH = 96;
const SPIKE_HEIGHT = 31;
const CONVEYOR_WIDTH = 96;
const CONVEYOR_HEIGHT = 16;
const FAKE_WIDTH = 97;
const FAKE_HEIGHT = 36;
const TRAMPOLINE_WIDTH = 97;
const TRAMPOLINE_HEIGHT = 22;
const TRAMPOLINE_FRAME_Y = 0;

// PLATFORM EFFECTS
const CONVEYOR_EFFECT = 2;
const TRAMPOLINE_EFFECT = 60;
